######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 26 21:58:42 2013
######################################################################

TEMPLATE = lib
CONFIG += shared
TARGET = ../core
DEPENDPATH += .
INCLUDEPATH += .
DEFINES += PINETD_CORE_LIBRARY

# Input
SOURCES += main.cpp
