######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 26 21:32:41 2013
######################################################################

TEMPLATE = app
TARGET = ../pinetd
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += silent

QT -= gui
QT += network

# Input
SOURCES += cli.cpp
